sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - ls
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project servian-coffee-prod
  - gcloud config set compute/zone australia-southeast1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t sshellien/react-test -f ./client/Dockerfile.dev ./client
  - echo Finished pre-install steps...

script:
  - echo Beginning script step...
  - docker run -e CI=true sshellien/react-test npm run test
  - echo Finished script step

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
